name: ClusterAPI
main: me.AdityaTD.ClusterAPI.Main
version: 0.1
website: http://www.youtube.com/user/adityatripathidelhi
author: AdityaTD
description: A Minecraft API for Bukkit & Spigot made by Developers by The Developers!